services:
  db:
    image: postgres:15-alpine
    container_name: kalyanna-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    networks:
      - kalyanna_network
    restart: unless-stopped
  bot:
    container_name: kalyanna-src
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
    depends_on:
      - db
    networks:
      - kalyanna_network
    restart: unless-stopped
    volumes:
      - ./src/db_backups:/app/db_backups
networks:
  kalyanna_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local